const fontOptions = [
  { label: "Arial", value: "Arial, sans-serif" },
  { label: "Georgia", value: "Georgia, serif" },
  { label: "Times New Roman", value: "'Times New Roman', Times, serif" },
  { label: "Verdana", value: "Verdana, sans-serif" },
  { label: "Courier New", value: "'Courier New', Courier, monospace" },
  { label: "Roboto", value: "'Roboto', sans-serif" },
  { label: "Montserrat", value: "'Montserrat', sans-serif" },
  { label: "Open Sans", value: "'Open Sans', sans-serif" },
  { label: "Lato", value: "'Lato', sans-serif" },
  { label: "Oswald", value: "'Oswald', sans-serif" },
  { label: "Raleway", value: "'Raleway', sans-serif" },
  { label: "Poppins", value: "'Poppins', sans-serif" },
  { label: "Merriweather", value: "'Merriweather', serif" },
  { label: "Nunito", value: "'Nunito', sans-serif" },
  { label: "Playfair Display", value: "'Playfair Display', serif" },
  { label: "Orbitron", value: "'Orbitron', sans-serif" },
  { label: "Audiowide", value: "'Audiowide', sans-serif" },
  { label: "Press Start 2P", value: "'Press Start 2P', cursive" },
  { label: "VT323", value: "'VT323', monospace" },
  { label: "Share Tech Mono", value: "'Share Tech Mono', monospace" },
  { label: "Exo 2", value: "'Exo 2', sans-serif" },
  { label: "Quantico", value: "'Quantico', sans-serif" },
  { label: "Aldrich", value: "'Aldrich', sans-serif" },
  { label: "Dancing Script", value: "'Dancing Script', cursive" },
  { label: "Amatic SC", value: "'Amatic SC', cursive" },
  { label: "Pacifico", value: "'Pacifico', cursive" },
  { label: "Lobster", value: "'Lobster', cursive" },
  { label: "Bangers", value: "'Bangers', cursive" },
  { label: "Fredericka the Great", value: "'Fredericka the Great', cursive" },
  { label: "Chewy", value: "'Chewy', cursive" },
  { label: "Baloo Bhai 2", value: "'Baloo Bhai 2', cursive" },
];

export default fontOptions;
